APT Test

diff --git a/bin/finalize b/bin/finalize
--- a/bin/finalize
+++ b/bin/finalize
@@ -24,6 +24,80 @@ CACHE_DIR=$2
 DEPS_DIR=$3
 DEPS_INDEX=$4
 
+OTP_VERSION="21.3.8.2"
+
+if [ -f ${BUILD_DIR}/.preferred_otp_version ]; then
+  OTP_VERSION=$(cat ${BUILD_DIR}/.preferred_otp_version)
+fi
+
+OTP_PACKAGE="OTP-${OTP_VERSION}.tar.gz"
+
+# --------------------
+
+home_dir=$(cd $(dirname $(dirname $0)); pwd)
+ERLROOT=${BUILD_DIR}/otp
+PROFILE=${BUILD_DIR}/.profile.d
+
+# --------------------
+
+
+echo "-------> Unpacking Erlang/OTP ${CACHE_DIR}/${OTP_PACKAGE}"
+mkdir -p ${ERLROOT}
+tar zxf ${CACHE_DIR}/${OTP_PACKAGE} -C ${ERLROOT} --strip-components=1
+
+echo "-------> Installing Erlang/OTP $OTP_VERSION"
+ln -s ${ERLROOT} /app/otp
+${ERLROOT}/Install -minimal /app/otp
+
+PATH=/app/otp/bin:$PATH
+export PATH
+
+cd $BUILD_DIR
+
+# Does rebar3 already exist?
+if [ ! -e "rebar3" ]; then
+  echo "-------> Installing Rebar from buildpack"
+  cp ${home_dir}/opt/rebar3 ./
+fi
+
+echo "-------> Building with Rebar3"
+unset GIT_DIR
+./rebar3 release 2>&1 | sed -u 's/^/         /'
+
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+  echo "-----> Build failed"
+  exit 1
+fi
+
+if [ -f ${home_dir}/opt/otp.sh ]; then
+  mkdir -p ${PROFILE}
+  cp ${HOME_DIR}/opt/otp.sh ${PROFILE}
+fi
+
+echo "-------> Build succeeded"
+exit 0
+
+echo "-------> Extracting Erlang OTP"
+
+## Install Erlang OTP
+#sudo dpkg -i ${CACHE_DIR}/${LIB_SCTP}
+#sudo dpkg --ignore-depends=libwxbase3.0-0v5,libwxgtk3.0-0v5 -i ${CACHE_DIR}/${OTP_PACKAGE}
+
+ERL_ROOT=${BUILD_DIR}/erlang
+PROFILE=${BUILD_DIR}/.profile.d
+
+mkdir -p ${ERL_ROOT}
+tar zxf ${CACHE_DIR}/${OTP_PACKAGE} -C ${ERL_ROOT} --strip-components=1
+
+echo "-------> Installing Erlang OTP"
+ln -s ${ERL_ROOT} /app/erlang
+${ERL_ROOT}/Install -minimal /app/erlang
+
+PATH=/app/erlang/bin:$PATH
+export PATH
+
+
+
 REBAR_CACHE_DIR="${CACHE_DIR}/rebar"
 
 home_dir=$(cd $(dirname $(dirname $0)); pwd)
